# Generated by Django 6.0.4 on 2026-05-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userprofile_bio_userprofile_last_seen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('action', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'accounts_activity',
                'managed': False,
            },
        ),
    ]
