# Generated by Django 6.0.2 on 2026-03-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_2FA_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
