# Generated by Django 6.0.2 on 2026-03-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_customuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("Admin", "Admin"), ("User", "User")],
                default="User",
                max_length=10,
            ),
        ),
    ]
